[package]
name = "json-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lexer"
path = "src/lib/lexer.rs"

[dependencies]
json = "0.12.4"
